#!python

"""Runs a batch of ``dms2_bcsubamp`` programs, summarizes results."""


import os
import glob
import sys
import re
import pandas
import dms_tools2.parseargs
import dms_tools2.utils


def main():
    """Main body of script."""

    parser = dms_tools2.parseargs.batch_bcsubampParser()
    args = vars(parser.parse_args())
    prog = parser.prog

    dms_tools2.utils.initLogger(sys.stdout, prog, args)

    assert os.path.isfile(args['batchfile']), "Cannot find batchfile"
    batchruns = pandas.read_csv(args['batchfile'])

    filesuffixes = {
            'nbarcodes':'nbarcodes.pdf',
            }



if __name__ == '__main__':
    main() # run the script
